### ISSUE TITLE
Require Zend Diactoros

### ISSUE THREAD

**Issue by loevgaard** [symfony/psr-http-message-bridge#34]
Why don't you require Zend Diactoros in composer.json?

Instead you choose to test whether it [exists](https://github.com/symfony/psr-http-message-bridge/blob/master/Factory/DiactorosFactory.php#L35).

**Comment by stof** [comment]
Because you can use any PSR-7 implementation for the PSR-7 -> HttpFoundation conversion (and so you don't need Diactoros if you use another one).

and initially, we also thought about implement HttpFoundation -> PSR-7 converters for other implementations than Diactoros, but we never did it (at that time, there was no other complete implementation of the ServerRequestInterface of PSR-7, as guzzlehttp/psr-7 is about client-side requests)

**Comment by loevgaard** [comment]
Thanks for the quick reply. I understand

**Comment by fabpot** [comment]
@loevgaard Can you close then.

**Comment by loevgaard** [comment]
See stof's [comment](https://github.com/symfony/psr-http-message-bridge/issues/34#issuecomment-324879355)
