### ISSUE TITLE
PSR factory class relies on PSR-17 interfaces but fig psr 17 package is not included in composer.json

### ISSUE THREAD

**Issue by przemoli** [symfony/psr-http-message-bridge#55]
This class depends on fig psr17 interfaces, but that package is missing from the composer:
https://github.com/symfony/psr-http-message-bridge/blob/master/Factory/PsrHttpFactory.php

Is that on purpose with an intent that user of the library will provide those interfaces with PSR17 implementation?

**Comment by stof** [comment]
Well, any package *implementing* these interfaces will already be depending on the fig package (as it will need the interfaces to be able to implement them).

We don't depend on the PSR-17 package, because the package is totally usable without using the PsrHttpFactory (you may be using the DiactorosFactory is you use diactoros 1.x for instance).

And anyway, a typehint does not create a dependency on the interface for our code (it creates one for the code writing the class you use to pass the argument), so things don't break here.

**Comment by przemoli** [comment]
Sorry, did not see "suggests" section in composer :(
