### ISSUE TITLE
Add UriFactoryInterface?

### ISSUE THREAD

**Issue by drupol** [symfony/psr-http-message-bridge#93]
Hello there,

I see that `Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory` doesn't have the `UriFactoryInterface` in its arguments.

Should we add it?

Thanks.

**Comment by nicolas-grekas** [comment]
I'm not sure I understand: where would this be needed?

**Comment by drupol** [comment]
After a second though, I was about to close this issue.
Of course, I understand that this is not needed in the context of https://github.com/symfony/psr-http-message-bridge/blob/main/Factory/PsrHttpFactory.php, and thus, not needed here.

However, if may be included in that class to convert a URI (Symfony string) to an `UriInterface` (PSR).

We could imagine to have a method like

```
public function createUri(string $uri): UriInterface;
```

WDYT?

**Comment by derrabus** [comment]
The purpose of the bridge is to map between HttpFoundation and PSR-7 by consuming PSR-17 factories. It does not provide its own PSR-7 implementation and does not know how to create a PSR-7 URI. All a potential `createUri` method could do is delegate to another `UriFactoryInterface` implementation. This is pretty much pointless, since you could consume the PSR-17 URI factory of your choice directly to achieve the same goal.

**Comment by drupol** [comment]
Fair enough, closing the issue.

Thanks for the explanation.
